language: generic
sudo: required
services:
  - docker


before_install: 
 - docker build -t shahban/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true shahban/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  enc: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-140407547776"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
